name: 'Rebol-Brotli CI'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.18.5

    - name: Build 32bit Rebol/Brotli extension
      run: ./siskin Rebol-Brotli.nest brotli-windows-x86.rebx

    - name: Prepare 32bit Rebol/Brotli extension
      run:  MOVE ./build/brotli-windows-x86.rebx ./brotli-windows-x86.rebx

    - name: Build 64bit Rebol/Brotli extension
      run: ./siskin Rebol-Brotli.nest brotli-windows-x64.rebx

    - name: Prepare 64bit Rebol/Brotli extension
      run:  MOVE ./build/brotli-windows-x64.rebx ./brotli-windows-x64.rebx

#    - name: Install Rebol for extension test
#      uses: oldes/install-rebol@v3.21.0
#      with:
#        product: Bulk
#
#    - name: Minimal Rebol/Brotli extension test
#      run:  ./rebol3 ci-test.r3

    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-Brotli-Windows-CI-${{github.run_id}}
        path: ./*.rebx

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.18.5

    - name: Build 64bit Rebol/Brotli extension
      run: ./siskin Rebol-Brotli.nest brotli-linux-x64

    - name: Prepare 64bit Rebol Brotli extension
      run:  mv ./build/brotli-linux-x64.so ./brotli.rebx

#    - name: Install Rebol for extension test
#      uses: oldes/install-rebol@v3.21.0
#      with:
#        product: Bulk
#
#    - name: Minimal Rebol/Brotli extension test
#      run:  ./rebol3 ci-test.r3

    - name: Compress 64bit Rebol/Brotli extension
      run:  |
        mv ./brotli.rebx ./brotli-linux-x64.rebx
        gzip -9 ./brotli-linux-x64.rebx

    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-Brotli-Linux-CI-${{github.run_id}}
        path: ./*.gz

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.18.5

    - name: Build 64bit Rebol/Brotli extension
      run: ./siskin Rebol-Brotli.nest brotli-macos-x64

    - name: Prepare 64bit Rebol Brotli extension
      run:  mv ./build/brotli-macos-x64.dylib ./brotli-macos-x64.rebx

    - name: Build 64bit Rebol/Brotli extension
      run: ./siskin Rebol-Brotli.nest brotli-macos-arm64

    - name: Prepare 64bit Rebol Brotli extension
      run:  mv ./build/brotli-macos-arm64.dylib ./brotli-macos-arm64.rebx

#    - name: Install Rebol for extension test
#      uses: oldes/install-rebol@v3.21.0
#      with:
#        product: Bulk
#
#    - name: Minimal Rebol/Brotli extension test
#      run:  ./rebol3 ci-test.r3

    - name: Compress x64 Rebol/Brotli extension
      run:  gzip -9 ./brotli-macos-x64.rebx

    - name: Compress arm64 Rebol/Brotli extension
      run:  gzip -9 ./brotli-macos-arm64.rebx

    - uses: actions/upload-artifact@v3
      with:
        name: Rebol-Brotli-macOS-CI-${{github.run_id}}
        path: ./*.gz

